services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-matexore}/loresuelvo-admin-webapp:main
    container_name: loresuelvo-admin-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    restart: unless-stopped
