export const sampleAuditLogsResponse = [
  {
    id: "aud-001",
    timestamp: "2026-09-28T14:30:00Z",
    operator_id: "op-101",
    operator_email: "operador@loresuelvo.com",
    action: "chat_access",
    resource_type: "operation",
    resource_id: "105",
    reason: "Investigación de reporte por posible fraude en la conversación",
    ip_address: "192.168.1.50",
    user_agent: "Mozilla/5.0 (Admin Console)",
    status: "success",
    metadata: { conversationId: 105 },
  },
  {
    id: "aud-002",
    timestamp: "2026-09-27T10:15:00Z",
    operator_id: "op-102",
    operator_email: "soporte@loresuelvo.com",
    action: "claim_resolution",
    resource_type: "claim",
    resource_id: "clm-204",
    reason: "Resolución de disputa económica a favor del consumidor",
    ip_address: "192.168.1.52",
    user_agent: "Mozilla/5.0 (Admin Console)",
    status: "success",
    metadata: { claimId: "clm-204" },
  },
];
