export const sampleAuditLogsResponse = [
  {
    id: "aud-001",
    timestamp: "2026-09-28T14:30:00Z",
    operator_id: "op-101",
    operator_email: "operador@loresuelvo.com",
    action: "chat_access",
    resource_type: "operation",
    resource_id: "105",
    reason: "Investigación de reporte por posible fraude en la conversación",
    ip_address: "192.168.1.50",
    user_agent: "Mozilla/5.0 (Admin Console)",
    status: "success",
    metadata: { conversationId: 105 },
  },
  {
    id: "aud-002",
    timestamp: "2026-09-27T10:15:00Z",
    operator_id: "op-102",
    operator_email: "soporte@loresuelvo.com",
    action: "claim_resolution",
    resource_type: "claim",
    resource_id: "clm-204",
    reason: "Resolución de disputa económica a favor del consumidor",
    ip_address: "192.168.1.52",
    user_agent: "Mozilla/5.0 (Admin Console)",
    status: "success",
    metadata: { claimId: "clm-204" },
  },
];

export const multiMonthAuditLogsResponse = [
  {
    id: "aud-003",
    timestamp: "2026-08-15T09:00:00Z",
    operator_id: "op-103",
    operator_email: "admin@loresuelvo.com",
    action: "category_create",
    resource_type: "category",
    resource_id: "cat-1",
    reason: "Creación de nueva categoría de servicios del hogar",
    ip_address: "192.168.1.40",
    user_agent: "Mozilla/5.0 (Admin Console)",
    status: "success",
    metadata: { categoryId: "cat-1" },
  },
  {
    id: "aud-004",
    timestamp: "2026-09-10T11:00:00Z",
    operator_id: "op-101",
    operator_email: "operador@loresuelvo.com",
    action: "provider_status_change",
    resource_type: "provider",
    resource_id: "prov-301",
    reason: "Habilitación de prestador tras validación de matrícula",
    ip_address: "192.168.1.50",
    user_agent: "Mozilla/5.0 (Admin Console)",
    status: "success",
    metadata: { providerId: "prov-301" },
  },
  {
    id: "aud-005",
    timestamp: "2026-09-18T16:20:00Z",
    operator_id: "op-102",
    operator_email: "soporte@loresuelvo.com",
    action: "review_moderation",
    resource_type: "review",
    resource_id: "rev-88",
    reason: "Ocultamiento de reseña ofensiva reportada",
    ip_address: "192.168.1.52",
    user_agent: "Mozilla/5.0 (Admin Console)",
    status: "success",
    metadata: { reviewId: "rev-88" },
  },
  {
    id: "aud-001",
    timestamp: "2026-09-28T14:30:00Z",
    operator_id: "op-101",
    operator_email: "operador@loresuelvo.com",
    action: "chat_access",
    resource_type: "operation",
    resource_id: "105",
    reason: "Investigación de reporte por posible fraude en la conversación",
    ip_address: "192.168.1.50",
    user_agent: "Mozilla/5.0 (Admin Console)",
    status: "success",
    metadata: { conversationId: 105 },
  },
];

