export const sampleClaimsListResponse = [
  {
    id: "clm-101",
    created_at: "2026-09-24T10:00:00Z",
    operation_id: 42,
    claimant_type: "consumer",
    claimant_name: "Ana Gómez",
    respondent_name: "Carlos López",
    category_name: "Plomería",
    status: "in_review",
    urgency: "high",
  },
  {
    id: "clm-102",
    created_at: "2026-09-22T14:30:00Z",
    operation_id: 43,
    claimant_type: "provider",
    claimant_name: "Martín Pérez",
    respondent_name: "Laura López",
    category_name: "Electricidad",
    status: "open",
    urgency: "medium",
  },
];

export const sampleFilterClaimsResponse = [
  {
    id: "clm-201",
    created_at: "2026-09-24T10:00:00Z",
    operation_id: 42,
    claimant_type: "consumer",
    claimant_name: "Carlos López",
    respondent_name: "Mariana Costa",
    category_name: "Plomería",
    status: "open",
    urgency: "high",
  },
  {
    id: "clm-202",
    created_at: "2026-09-23T11:00:00Z",
    operation_id: 43,
    claimant_type: "provider",
    claimant_name: "Laura López",
    respondent_name: "Gustavo Ruiz",
    category_name: "Gas",
    status: "resolved",
    urgency: "medium",
  },
  {
    id: "clm-203",
    created_at: "2026-09-22T09:30:00Z",
    operation_id: 44,
    claimant_type: "consumer",
    claimant_name: "Pedro Martínez",
    respondent_name: "Marcos Díaz",
    category_name: "Pintura",
    status: "open",
    urgency: "low",
  },
  {
    id: "clm-204",
    created_at: "2026-09-21T16:00:00Z",
    operation_id: 45,
    claimant_type: "provider",
    claimant_name: "Juan Silva",
    respondent_name: "María Romero",
    category_name: "Cerrajería",
    status: "dismissed",
    urgency: "low",
  },
];
