export const sampleReportedReviewsListResponse = [
  {
    id: "rev-101",
    created_at: "2026-09-25T14:00:00Z",
    operation_id: 101,
    author_name: "Lucía Fernández",
    provider_name: "Roberto Gómez",
    rating: 1,
    comment: "El trabajo fue pésimo y además me insultó al retirarse.",
    status: "reported",
    report_reason: "Lenguaje agraviante y trato ofensivo",
    moderation: null,
  },
  {
    id: "rev-102",
    created_at: "2026-09-24T18:30:00Z",
    operation_id: 102,
    author_name: "Esteban Morales",
    provider_name: "Clara Domínguez",
    rating: 2,
    comment: "Publicó mis datos personales en la respuesta.",
    status: "reported",
    report_reason: "Divulgación de datos personales",
    moderation: null,
  },
];

export const sampleMixedReviewsListResponse = [
  {
    id: "rev-201",
    created_at: "2026-09-25T10:00:00Z",
    operation_id: 201,
    author_name: "Gonzalo Arias",
    provider_name: "Valeria Ríos",
    rating: 5,
    comment: "Excelente servicio y puntualidad.",
    status: "visible",
    report_reason: null,
    moderation: null,
  },
  {
    id: "rev-202",
    created_at: "2026-09-24T11:00:00Z",
    operation_id: 202,
    author_name: "Mariana Paz",
    provider_name: "Esteban Quito",
    rating: 1,
    comment: "El técnico cobró de más y fue agresivo.",
    status: "reported",
    report_reason: "Lenguaje abusivo",
    moderation: null,
  },
  {
    id: "rev-203",
    created_at: "2026-09-23T15:00:00Z",
    operation_id: 203,
    author_name: "Lucas Benítez",
    provider_name: "Florencia Peña",
    rating: 1,
    comment: "Contenido difamatorio y ofensivo.",
    status: "hidden",
    report_reason: "Lenguaje ofensivo hacia el prestador",
    moderation: {
      moderated_by: "Operador Admin",
      moderated_at: "2026-09-23T16:00:00Z",
      category: "abusive_language",
      reason: "Uso explícito de agravios e insultos",
    },
  },
];
